name: app.qfield.cloud APIs status
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  prod:
    runs-on: ubuntu-18.04
    steps:
      - name: Check
        run: curl -f https://app.qfield.cloud/api/v1/status/
